
package Vista;

/**
 *
 * @author CST-UTJ
 */
public class AnadirPropiedad extends javax.swing.JPanel {

    /**
     * Creates new form AnadirPropiedad
     */
    public AnadirPropiedad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonColoredAction1 = new org.edisoncor.gui.button.ButtonColoredAction();
        PanAñadirPropiedad = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtMetroPorPrecio = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        btnGuardarNuevaPropiedad = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        clockDigital1 = new org.edisoncor.gui.varios.ClockDigital();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDueño = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMetrosCuadrados = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtTipoDeNegocio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        comboBoxRound1 = new org.edisoncor.gui.comboBox.ComboBoxRound();

        buttonColoredAction1.setText("buttonColoredAction1");

        setBackground(new java.awt.Color(143, 198, 94));

        PanAñadirPropiedad.setBackground(new java.awt.Color(233, 248, 223));
        PanAñadirPropiedad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanAñadirPropiedad.setLayout(null);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        PanAñadirPropiedad.add(jSeparator1);
        jSeparator1.setBounds(520, 60, 20, 420);

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel1.setText("Direccion");
        PanAñadirPropiedad.add(jLabel1);
        jLabel1.setBounds(80, 170, 120, 21);

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel7.setText("Descripción");
        PanAñadirPropiedad.add(jLabel7);
        jLabel7.setBounds(670, 310, 110, 21);

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel8.setText("Precio por metro");
        PanAñadirPropiedad.add(jLabel8);
        jLabel8.setBounds(70, 420, 120, 21);

        txtDireccion.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        PanAñadirPropiedad.add(txtDireccion);
        txtDireccion.setBounds(320, 160, 150, 30);

        txtMetroPorPrecio.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        PanAñadirPropiedad.add(txtMetroPorPrecio);
        txtMetroPorPrecio.setBounds(320, 420, 140, 30);

        txtDescripcion.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        PanAñadirPropiedad.add(txtDescripcion);
        txtDescripcion.setBounds(810, 300, 150, 30);

        btnGuardarNuevaPropiedad.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnGuardarNuevaPropiedad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/guardar.png"))); // NOI18N
        btnGuardarNuevaPropiedad.setText("Guardar ");
        btnGuardarNuevaPropiedad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardarNuevaPropiedad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanAñadirPropiedad.add(btnGuardarNuevaPropiedad);
        btnGuardarNuevaPropiedad.setBounds(470, 490, 120, 50);

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel10.setText("Añadir Propiedad");
        PanAñadirPropiedad.add(jLabel10);
        jLabel10.setBounds(430, 20, 180, 30);

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        PanAñadirPropiedad.add(jSeparator3);
        jSeparator3.setBounds(0, 60, 520, 10);

        clockDigital1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        PanAñadirPropiedad.add(clockDigital1);
        clockDigital1.setBounds(920, 500, 100, 49);

        jLabel12.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel12.setText("Nombre");
        PanAñadirPropiedad.add(jLabel12);
        jLabel12.setBounds(90, 100, 140, 21);

        jLabel13.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel13.setText("Dueño");
        PanAñadirPropiedad.add(jLabel13);
        jLabel13.setBounds(90, 240, 100, 21);

        txtNombre.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        PanAñadirPropiedad.add(txtNombre);
        txtNombre.setBounds(320, 100, 150, 30);

        txtDueño.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        txtDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDueñoActionPerformed(evt);
            }
        });
        PanAñadirPropiedad.add(txtDueño);
        txtDueño.setBounds(320, 230, 150, 30);

        txtTipo.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        PanAñadirPropiedad.add(txtTipo);
        txtTipo.setBounds(320, 290, 150, 30);

        jLabel14.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel14.setText("Tipo");
        PanAñadirPropiedad.add(jLabel14);
        jLabel14.setBounds(100, 300, 90, 21);

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel2.setText("Metros Cuadrados");
        PanAñadirPropiedad.add(jLabel2);
        jLabel2.setBounds(70, 360, 160, 30);

        txtMetrosCuadrados.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        PanAñadirPropiedad.add(txtMetrosCuadrados);
        txtMetrosCuadrados.setBounds(320, 360, 150, 30);

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel3.setText("Precio");
        PanAñadirPropiedad.add(jLabel3);
        jLabel3.setBounds(680, 240, 90, 21);

        txtPrecio.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        PanAñadirPropiedad.add(txtPrecio);
        txtPrecio.setBounds(810, 230, 150, 30);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        PanAñadirPropiedad.add(jSeparator2);
        jSeparator2.setBounds(520, 60, 530, 30);

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel4.setText("Tipo de negocio");
        PanAñadirPropiedad.add(jLabel4);
        jLabel4.setBounds(660, 160, 110, 30);

        txtTipoDeNegocio.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        PanAñadirPropiedad.add(txtTipoDeNegocio);
        txtTipoDeNegocio.setBounds(810, 160, 150, 30);

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel9.setText("Número de Ciudad");
        PanAñadirPropiedad.add(jLabel9);
        jLabel9.setBounds(650, 380, 130, 20);

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        PanAñadirPropiedad.add(jSeparator4);
        jSeparator4.setBounds(0, 480, 1030, 20);
        PanAñadirPropiedad.add(comboBoxRound1);
        comboBoxRound1.setBounds(840, 380, 110, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(PanAñadirPropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 1034, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(PanAñadirPropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDueñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDueñoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanAñadirPropiedad;
    public javax.swing.JButton btnGuardarNuevaPropiedad;
    private org.edisoncor.gui.button.ButtonColoredAction buttonColoredAction1;
    private org.edisoncor.gui.varios.ClockDigital clockDigital1;
    private org.edisoncor.gui.comboBox.ComboBoxRound comboBoxRound1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JTextField txtDescripcion;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtDueño;
    public javax.swing.JTextField txtMetroPorPrecio;
    public javax.swing.JTextField txtMetrosCuadrados;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtPrecio;
    public javax.swing.JTextField txtTipo;
    public javax.swing.JTextField txtTipoDeNegocio;
    // End of variables declaration//GEN-END:variables
}
