package Vista;

import java.awt.Dimension;

/**
 *
 * @author CST-UTJ
 */
public class DashBoard extends javax.swing.JPanel {


    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
        barraOff();
    }

    public void porcentaje(int p){
        Thread hilo = new Thread(){
            @Override
            public void run() {
                Dimension tam = panBarra.getSize();
                panProgreso.setSize((p*tam.width)/100, tam.height);
            }
        };
        hilo.start();
    }
    
    public void barraOff(){
        try {Thread.sleep(100);} catch (InterruptedException ex) {}
        panBarra.setVisible(false);
    }
    
    public void barraOn(){
        panBarra.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashPropiedades = new javax.swing.JButton();
        dashCitas = new javax.swing.JButton();
        dashUsuarios = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        dashCerrarSesion = new javax.swing.JButton();
        panBarra = new org.edisoncor.gui.panel.PanelNice();
        panProgreso = new org.edisoncor.gui.panel.PanelNice();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        dashPropiedades.setBackground(new java.awt.Color(255, 255, 255));
        dashPropiedades.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        dashPropiedades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/casa.png"))); // NOI18N
        dashPropiedades.setText("Propiedades");
        dashPropiedades.setBorder(null);
        dashPropiedades.setBorderPainted(false);
        dashPropiedades.setContentAreaFilled(false);
        dashPropiedades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashPropiedades.setFocusPainted(false);

        dashCitas.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        dashCitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/cuaderno.png"))); // NOI18N
        dashCitas.setText("Citas");
        dashCitas.setBorderPainted(false);
        dashCitas.setContentAreaFilled(false);
        dashCitas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashCitas.setFocusPainted(false);
        dashCitas.setMaximumSize(new java.awt.Dimension(99, 25));
        dashCitas.setMinimumSize(new java.awt.Dimension(99, 25));
        dashCitas.setPreferredSize(new java.awt.Dimension(99, 25));

        dashUsuarios.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        dashUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/usuario.png"))); // NOI18N
        dashUsuarios.setText("Usuarios");
        dashUsuarios.setBorderPainted(false);
        dashUsuarios.setContentAreaFilled(false);
        dashUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashUsuarios.setFocusPainted(false);
        dashUsuarios.setMaximumSize(new java.awt.Dimension(99, 25));
        dashUsuarios.setMinimumSize(new java.awt.Dimension(99, 25));
        dashUsuarios.setPreferredSize(new java.awt.Dimension(99, 25));

        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jSeparator3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jSeparator4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/LogoDefinitiva.jpg"))); // NOI18N

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 152, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        dashCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        dashCerrarSesion.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        dashCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/cerrar-sesion.png"))); // NOI18N
        dashCerrarSesion.setText(" Cerrar sesión");
        dashCerrarSesion.setBorderPainted(false);
        dashCerrarSesion.setContentAreaFilled(false);
        dashCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashCerrarSesion.setFocusPainted(false);
        dashCerrarSesion.setMaximumSize(new java.awt.Dimension(99, 25));
        dashCerrarSesion.setMinimumSize(new java.awt.Dimension(99, 25));
        dashCerrarSesion.setPreferredSize(new java.awt.Dimension(99, 25));

        panBarra.setBackground(new java.awt.Color(190, 235, 159));

        panProgreso.setBackground(new java.awt.Color(40, 153, 118));

        javax.swing.GroupLayout panBarraLayout = new javax.swing.GroupLayout(panBarra);
        panBarra.setLayout(panBarraLayout);
        panBarraLayout.setHorizontalGroup(
            panBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBarraLayout.createSequentialGroup()
                .addComponent(panProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panBarraLayout.setVerticalGroup(
            panBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panProgreso, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addComponent(dashCitas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dashPropiedades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator3)
            .addComponent(dashUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator4)
            .addComponent(dashCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(panelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(panBarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(panelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(dashPropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(dashCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(dashUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(dashCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(panBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton dashCerrarSesion;
    public javax.swing.JButton dashCitas;
    public javax.swing.JButton dashPropiedades;
    public javax.swing.JButton dashUsuarios;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private org.edisoncor.gui.panel.PanelNice panBarra;
    private org.edisoncor.gui.panel.PanelNice panProgreso;
    public org.edisoncor.gui.panel.PanelImage panelImage2;
    // End of variables declaration//GEN-END:variables
}
