
package Vista;

/**
 *
 * @author CST-UTJ
 */
public class InformacionDePropiedades extends javax.swing.JPanel {

    /**
     * Creates new form InformacionDePropiedades
     */
    public InformacionDePropiedades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        PanDetalles = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        clockDigital1 = new org.edisoncor.gui.varios.ClockDigital();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetalles = new rojerusan.RSTableMetro();

        setBackground(new java.awt.Color(143, 198, 94));

        PanDetalles.setBackground(new java.awt.Color(223, 248, 223));
        PanDetalles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel1.setText("Detalles");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        tblDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", ""},
                {"", "", "", ""},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Calle", "Número de Casa", "Codigo Postal", "Descripción"
            }
        ));
        tblDetalles.setColorBackgoundHead(new java.awt.Color(40, 153, 118));
        tblDetalles.setColorFilasBackgound2(new java.awt.Color(233, 248, 223));
        tblDetalles.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblDetalles.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblDetalles.setColorSelBackgound(new java.awt.Color(0, 0, 0));
        tblDetalles.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tblDetalles.setFuenteFilas(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tblDetalles.setFuenteFilasSelect(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tblDetalles.setFuenteHead(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jScrollPane2.setViewportView(tblDetalles);

        javax.swing.GroupLayout PanDetallesLayout = new javax.swing.GroupLayout(PanDetalles);
        PanDetalles.setLayout(PanDetallesLayout);
        PanDetallesLayout.setHorizontalGroup(
            PanDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanDetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1015, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanDetallesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(clockDigital1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(PanDetallesLayout.createSequentialGroup()
                .addGap(463, 463, 463)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanDetallesLayout.setVerticalGroup(
            PanDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanDetallesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clockDigital1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(PanDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(PanDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel PanDetalles;
    private org.edisoncor.gui.varios.ClockDigital clockDigital1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public rojerusan.RSTableMetro tblDetalles;
    // End of variables declaration//GEN-END:variables
}
